// Generated by scripts/waveform-peaks.mjs — do not edit by hand.
// Per-file waveform bar heights (px) and duration (s) for the call samples,
// precomputed so the page never downloads the MP3s until Play is pressed.

export type CallSampleWaveform = { duration: number; heights: number[] };

export const CALL_SAMPLE_WAVEFORMS: Record<string, CallSampleWaveform> = {
  "/assets/call-sample-1.mp3": {
    duration: 92.24,
    heights: [16.9, 17.4, 23.7, 16.1, 11.3, 13.3, 13.3, 23.3, 19.5, 18.9, 16.5, 18, 12.5, 16.3, 14.1, 22.3, 19.2, 12.4, 19.1, 19.7, 19.5, 30, 15.9, 13.1, 22.7, 15.5, 13.5, 22.7, 16, 19.2],
  },
  "/assets/call-sample-2.mp3": {
    duration: 107.7,
    heights: [24, 23.5, 14.7, 22.4, 28.2, 20.6, 21.7, 18.2, 30, 17.5, 23.4, 17.5, 12, 11.7, 12.2, 24.4, 20.3, 26.7, 29.7, 23.2, 22, 23.8, 13.6, 9.6, 21.3, 11, 29.1, 28.4, 21.9, 25.1],
  },
  "/assets/call-sample-3.mp3": {
    duration: 100.02,
    heights: [25.1, 30, 18.9, 22.9, 10.1, 19.3, 21.3, 18.5, 22.7, 15.4, 21.4, 14.4, 28.5, 27.6, 22.8, 18.4, 15, 14.8, 16.8, 18.2, 15.4, 19.5, 22.8, 20.3, 18.3, 20, 14.7, 17.5, 19.6, 21.6],
  },
};
