// GENERATED by scripts/webflow/transform.mjs — do not hand-edit the array
// contents below (frontmatter-less news items have no source file of their
// own to edit instead); re-run the migration script to regenerate. Safe to
// hand-edit anything OUTSIDE the generated block (types, helpers).
//
// Migrated from Webflow's "news-articles" collection. No date field exists
// on that collection — `date` is each item's Webflow `createdOn` timestamp.
// 9 of the original 18 items were the same seed-funding press release
// syndicated across outlets; collapsed to one entry per
// scripts/webflow/overrides.json (see that file's "news" section for the
// exact grouping and why).
//
// Plain data, no filesystem access — safe to import from client components
// (NewsExplorer.tsx does, as a type-only import).

export type NewsPost = {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  date: string;
  thumb: string;
  /** External press URL — every migrated news item is outbound coverage,
   * not an on-site article (Webflow's collection has no body field). */
  articleUrl: string;
  /** Display name of the outlet, derived from articleUrl's hostname. */
  source?: string;
  location?: string;
  featured?: boolean;
};

export const CATEGORIES: readonly string[] = [
  "Press Releases",
  "Partnerships",
  "Featured in"
];

// prettier-ignore
export const NEWS_POSTS: NewsPost[] = [
  {
    "slug": "fdcpa-compliant-voice-ai-tools-for-debt-collection-2026",
    "title": "FDCPA-Compliant Voice AI Tools for Debt Collection (2026)",
    "excerpt": "Platforms like Vodex, automate voice conversations for debt collection while maintaining FDCPA, TCPA, and Regulation F compliance through built-in regulatory engines, automated disclosure delivery, and consent documentation.",
    "category": "Featured in",
    "date": "2026-05-22",
    "thumb": "/assets/news/fdcpa-compliant-voice-ai-tools-for-debt-collection-2026.png",
    "articleUrl": "https://startupfinanceguide.com/startup-finance/fdcpa-compliant-voice-ai-debt-collection-2026",
    "source": "Startup Finance Guide",
    "featured": true
  },
  {
    "slug": "how-vodex-ai-is-betting-on-speech-as-the-next-big-leap-in-enterprise-tech",
    "title": "How Vodex AI Is Betting on Speech as the Next Big Leap in Enterprise Tech",
    "excerpt": "While voice was already a trillion-dollar market that powered everything from banking kiosks to airport assistants, Kumar noted that the technology was stuck when it came to phone calls, one of the biggest use cases by far.",
    "category": "Featured in",
    "date": "2025-09-12",
    "thumb": "/assets/news/how-vodex-ai-is-betting-on-speech-as-the-next-big-leap-in-enterprise-tech.png",
    "articleUrl": "https://prodwrks.com/how-vodex-ai-is-betting-on-speech-as-the-next-big-leap-in-enterprise-tech/",
    "source": "ProdWrks",
    "location": "India"
  },
  {
    "slug": "discover-the-power-of-fully-compliant-ai-voice-agents-for-debt-collection-with-vodex-ai-at-rmai-2025",
    "title": "Discover the Power of Fully Compliant AI Voice Agents for Debt Collection with Vodex.ai at RMAi 2025",
    "excerpt": "Vodex.ai, a cutting-edge innovator in fully compliant AI-powered voice solutions for debt collection, is thrilled to attend the Receivables Management Association International (RMAi) 2025 Annual Conference. Scheduled for February 10th to 13th, 2025, in Las Vegas, this premier event brings together the brightest minds in receivables management to explore transformative advancements.",
    "category": "Press Releases",
    "date": "2025-02-05",
    "thumb": "/assets/news/discover-the-power-of-fully-compliant-ai-voice-agents-for-debt-collection-with-vodex-ai-at-rmai-2025.png",
    "articleUrl": "https://www.prnewswire.com/news-releases/discover-the-power-of-fully-compliant-ai-voice-agents-for-debt-collection-with-vodexai-at-rmai-2025-302364310.html",
    "source": "PR Newswire"
  },
  {
    "slug": "introducing-the-2024-class-of-google-for-startups-accelerator-ai-first",
    "title": "Introducing the 2024 Class of Google for Startups Accelerator: AI First",
    "excerpt": "At Google, we are proud to support and work with some of these top startups through the Google for Startups Accelerator program. To highlight a few examples from our recent AI-focused cohorts..",
    "category": "Featured in",
    "date": "2025-01-06",
    "thumb": "/assets/news/introducing-the-2024-class-of-google-for-startups-accelerator-ai-first.png",
    "articleUrl": "https://blog.google/intl/en-in/introducing-the-2024-class-of-google-for-startups-accelerator-ai-first/",
    "source": "Google"
  },
  {
    "slug": "krisp-and-vodex-partner-to-perfect-genai-powered-voicebot-calls-for-high-quality-lead-qualification",
    "title": "Krisp and Vodex Partner to Perfect GenAI-Powered Voicebot Calls for High-Quality Lead Qualification",
    "excerpt": "Krisp, the world’s leading AI-powered voice productivity software, today announced a new integration with Vodex’s AI-powered voicebots, The partnership delivers Krisp’s advanced AI Noise Cancellation as part of their...",
    "category": "Partnerships",
    "date": "2025-01-03",
    "thumb": "/assets/news/krisp-and-vodex-partner-to-perfect-genai-powered-voicebot-calls-for-high-quality-lead-qualification.png",
    "articleUrl": "https://krisp.ai/blog/krisp-and-vodex-partnership/",
    "source": "Krisp"
  },
  {
    "slug": "the-best-of-inc42s-30-startups-to-watch",
    "title": "The Best Of Inc42’s 30 Startups To Watch",
    "excerpt": "As we stand on the cusp of 2025, it is time to glean the spotlight on some of the hottest startups that caught our attention in 2024. The startup offers an AI-powered sales agent for outbound calls that can automate..",
    "category": "Featured in",
    "date": "2025-01-03",
    "thumb": "/assets/news/the-best-of-inc42s-30-startups-to-watch.png",
    "articleUrl": "https://inc42.com/startups/2024-in-review-the-best-of-inc42s-30-startups-to-watch/",
    "source": "Inc42"
  },
  {
    "slug": "forbes-india-dgems24-select-200-companies-with-global-business-potential",
    "title": "Forbes India DGEMS'24 Select 200 Companies With Global Business Potential",
    "excerpt": "Vodex has been selected as one of the 200 companies at Forbes India-DGEMS 2024. This recognition celebrates global business potential and highlights our founders Anshul Shrivastava & Kumar Saurav as ‘eXtrepreneurs...",
    "category": "Featured in",
    "date": "2024-11-27",
    "thumb": "/assets/news/forbes-india-dgems24-select-200-companies-with-global-business-potential.jpg",
    "articleUrl": "https://images.news18.com/ms/prod/forbesindia/Vodex_c5ae8b2a84.pdf",
    "source": "Forbes India"
  },
  {
    "slug": "unlocking-the-power-of-ai-driven-sales-vodex-ai",
    "title": "Unlocking the Power of AI-Driven Sales: Vodex AI",
    "excerpt": "Imagine a future where AI seamlessly handles thousands of personalized customer interactions in mere minutes, lead nurturing becomes an art form executed with machine-like precision, and sales teams can focus on what truly matters – closing deals...",
    "category": "Featured in",
    "date": "2024-11-04",
    "thumb": "/assets/news/unlocking-the-power-of-ai-driven-sales-vodex-ai.jpg",
    "articleUrl": "https://businessreviewlive.com/unlocking-the-power-of-ai-driven-sales-vodex-ai/",
    "source": "Business Review Live"
  },
  {
    "slug": "vodex-raises-2m-seed-funding",
    "title": "Vodex Raises $2M in Seed Funding to Power AI Voice Agents for Collections",
    "excerpt": "Vodex, a pioneering Gen AI company, today announced that it has raised $2 million in a seed round from Unicorn India Ventures, and Pentathlon Ventures.",
    "category": "Press Releases",
    "date": "2024-08-23",
    "thumb": "/assets/news/vodex-raises-2m-seed-funding.png",
    "articleUrl": "https://www.prnewswire.com/news-releases/vodex-powers-up-with-2-million-seed-investment-for-gen-ai-sales-boost-302107296.html",
    "source": "PR Newswire",
    "location": "Bangalore, India"
  }
];

export function getFeaturedPost(): NewsPost {
  return NEWS_POSTS.find((post) => post.featured) ?? NEWS_POSTS[0];
}

export function getGridPosts(): NewsPost[] {
  const featured = getFeaturedPost();
  return NEWS_POSTS.filter((post) => post.slug !== featured.slug);
}
