// GENERATED by scripts/webflow/transform.mjs — do not hand-edit the array
// contents below; re-run the migration script to regenerate. Safe to
// hand-edit anything OUTSIDE the generated block (types, helpers).
//
// Migrated from Webflow's "videos" collection (all real, published YouTube
// videos). No duration field exists on that collection, so VideoCard no
// longer shows one. Videos open in an on-page modal (VideoLightbox) rather
// than linking off-site — see components/ui/VideoThumbButton.tsx.

export type Video = {
  slug: string;
  title: string;
  description: string;
  /** Single display category, picked from `categories` by precedence
   * (scripts/webflow/overrides.json) when a video carries more than one. */
  category: string;
  /** Every category this video is actually tagged with, for filtering. */
  categories: string[];
  date: string;
  thumb: string;
  youtubeId: string;
  featured?: boolean;
};

export const VIDEO_CATEGORIES: readonly string[] = [
  "Product",
  "Tutorials",
  "Podcasts / Interviews",
  "Overview"
];

// prettier-ignore
export const VIDEOS: Video[] = [
  {
    "slug": "growth-m-a-and-the-rise-of-smart-tech-in-collections-the-vodex-podcast-episode-3",
    "title": "Growth, M&A, and the Rise of Smart Tech in Collections | The Vodex Podcast Episode 3",
    "description": "Together with Vodex Co-founder & CEO Anshul Shrivastava, Michael unpacks: – Why ARM and collections firms are consolidating faster than ever – How tech-forward infrastructure, compliance, and voice AI shape valuations – What private equity and strategic buyers really look for today",
    "category": "Podcasts / Interviews",
    "categories": [
      "Podcasts / Interviews",
      "Overview"
    ],
    "date": "2025-10-15",
    "thumb": "/assets/videos/growth-m-a-and-the-rise-of-smart-tech-in-collections-the-vodex-podcast-episode-3.webp",
    "youtubeId": "8juXwi0yjMY",
    "featured": true
  },
  {
    "slug": "what-a-modern-collections-tech-stack-should-look-like-the-vodex-podcast-episode-2",
    "title": "What a Modern Collections Tech Stack Should Look Like | The Vodex Podcast | Episode 2",
    "description": "In this episode, our host Anshul Shrivastava, Co-founder & CEO of Vodex.ai, sits down with Rob Grafrath, founder of Grafrath Consulting.",
    "category": "Podcasts / Interviews",
    "categories": [
      "Podcasts / Interviews"
    ],
    "date": "2025-10-15",
    "thumb": "/assets/videos/what-a-modern-collections-tech-stack-should-look-like-the-vodex-podcast-episode-2.webp",
    "youtubeId": "kAC6MjDZiPA"
  },
  {
    "slug": "beyond-cascades-to-speech-to-speech-anshul-shrivastava-kumar-saurav-co-founders-at-vodex-ai",
    "title": "Beyond Cascades to Speech-to-Speech | Anshul Shrivastava & Kumar Saurav (Co-Founders at Vodex.ai)",
    "description": "Voice AI still hasn’t had its ChatGPT moment because people hate talking to bots that feel slow or robotic...",
    "category": "Podcasts / Interviews",
    "categories": [
      "Podcasts / Interviews",
      "Overview"
    ],
    "date": "2025-09-12",
    "thumb": "/assets/videos/beyond-cascades-to-speech-to-speech-anshul-shrivastava-kumar-saurav-co-founders-at-vodex-ai.webp",
    "youtubeId": "6EfeNvJBj2I"
  },
  {
    "slug": "the-smartest-voice-ai-for-sales-collections-calls",
    "title": "The Smartest Voice AI for Sales & Collections Calls",
    "description": "Experience the next generation of AI voice agents with Vodex.ai – built to handle sales, collections, and customer engagement at scale.",
    "category": "Product",
    "categories": [
      "Product",
      "Overview"
    ],
    "date": "2025-06-19",
    "thumb": "/assets/videos/the-smartest-voice-ai-for-sales-collections-calls.webp",
    "youtubeId": "fXJei_ysfDE"
  },
  {
    "slug": "vodex-dashboard-overview-episode-8",
    "title": "Vodex Dashboard Overview | Episode 8",
    "description": "Learn how to navigate your workspace, monitor campaign performance, track usage metrics, and access key settings — all from one place",
    "category": "Tutorials",
    "categories": [
      "Tutorials"
    ],
    "date": "2025-06-17",
    "thumb": "/assets/videos/vodex-dashboard-overview-episode-8.png",
    "youtubeId": "WMv_xqBgYTw"
  },
  {
    "slug": "where-to-set-up-whatsapp-sms-email-in-vodex-episode-7",
    "title": "Where to Set Up WhatsApp, SMS & Email in Vodex | Episode 7",
    "description": "In this quick walkthrough, we show you exactly where to set up WhatsApp, SMS, and Email channels inside Vodex.",
    "category": "Tutorials",
    "categories": [
      "Tutorials"
    ],
    "date": "2025-06-17",
    "thumb": "/assets/videos/where-to-set-up-whatsapp-sms-email-in-vodex-episode-7.png",
    "youtubeId": "W-Xsqb1uXYs"
  },
  {
    "slug": "how-to-configure-call-settings-on-vodex",
    "title": "How to Configure Call Settings on Vodex | Episode 6",
    "description": "In Episode 6 of the Vodex Tutorial Series, we walk you through how to configure your call settings for optimal performance.",
    "category": "Tutorials",
    "categories": [
      "Tutorials"
    ],
    "date": "2025-06-17",
    "thumb": "/assets/videos/how-to-configure-call-settings-on-vodex.png",
    "youtubeId": "5jPZ0zp1r2k"
  },
  {
    "slug": "how-to-create-campaign-insights-on-vodex-ai",
    "title": "How to Create Campaign Insights on Vodex | Episode 5",
    "description": "In this episode, we walk you through how to create Campaign Insights, a powerful feature that lets you ask specific questions about your campaign performance and get instant, actionable answers.",
    "category": "Tutorials",
    "categories": [
      "Tutorials"
    ],
    "date": "2025-06-10",
    "thumb": "/assets/videos/how-to-create-campaign-insights-on-vodex-ai.png",
    "youtubeId": "gIGUq_PPnAs"
  },
  {
    "slug": "how-to-create-a-campaign-on-vodex-ai-step-by-step-tutorial-episode-4",
    "title": "How to Create a Campaign on Vodex.ai | Episode 4",
    "description": "In Episode 4 of our Vodex tutorial series, we walk you through how to create and launch a campaign using Vodex.ai's voice automation platform",
    "category": "Tutorials",
    "categories": [
      "Tutorials"
    ],
    "date": "2025-06-10",
    "thumb": "/assets/videos/how-to-create-a-campaign-on-vodex-ai-step-by-step-tutorial-episode-4.png",
    "youtubeId": "8nsHstTBz8M"
  },
  {
    "slug": "how-to-add-an-audience-list-to-your-project-episode-3",
    "title": "How to Add an Audience List to Your Project | Episode 3",
    "description": "In this quick guide, we’ll show you how to upload and manage your contact list inside Vodex — so you can get your campaigns up and running faster",
    "category": "Tutorials",
    "categories": [
      "Tutorials"
    ],
    "date": "2025-06-10",
    "thumb": "/assets/videos/how-to-add-an-audience-list-to-your-project-episode-3.png",
    "youtubeId": "U_96TQGXMT4"
  },
  {
    "slug": "how-to-create-a-project-and-on-vodex-ai-episode-2",
    "title": "How to Create a Project and on Vodex.ai | Episode 2",
    "description": "In this quick tutorial, we’ll walk you through how to create a new project and setup an AI Voice Agent in Vodex.ai Whether you're setting up your first AI calling workflow or organizing multiple campaigns, this is where it all begins.",
    "category": "Tutorials",
    "categories": [
      "Tutorials"
    ],
    "date": "2025-06-10",
    "thumb": "/assets/videos/how-to-create-a-project-and-on-vodex-ai-episode-2.png",
    "youtubeId": "9QdEPWjEu-8"
  },
  {
    "slug": "getting-started-with-vodex-ai-episode-1-create-your-account",
    "title": "Getting Started with Vodex.ai: Episode 1: Create Your Account",
    "description": "In this quick tutorial, we’ll walk you through how to create your account on Vodex.ai and get started with our AI-powered voice automation platform",
    "category": "Tutorials",
    "categories": [
      "Tutorials"
    ],
    "date": "2025-06-10",
    "thumb": "/assets/videos/getting-started-with-vodex-ai-episode-1-create-your-account.png",
    "youtubeId": "IKUtxxBTLEs"
  },
  {
    "slug": "debt-collection-meets-ai-whats-changing-and-what-comes-next-the-vodex-podcast",
    "title": "Debt Collection Meets AI: What’s Changing and What Comes Next",
    "description": "In this inaugural episode of The Vodex Podcast, host Anshul Shrivastava (CEO, Vodex.ai) speaks with Susan Richards, Founder & CEO of CredTech Consulting LLC — a veteran of the ARM industry with 36+ years of experience across compliance, operations, and leadership.",
    "category": "Podcasts / Interviews",
    "categories": [
      "Podcasts / Interviews"
    ],
    "date": "2025-06-07",
    "thumb": "/assets/videos/debt-collection-meets-ai-whats-changing-and-what-comes-next-the-vodex-podcast.webp",
    "youtubeId": "tKpfBHQGy_A"
  },
  {
    "slug": "ai-voice-agents-for-debt-collection",
    "title": "AI Voice Agents for Debt collection",
    "description": "Vodex’s Gen AI-powered agents automate payment reminder calls, ensuring timely follow-ups with your clients. Our AI agents handle the entire process efficiently, reducing manual effort and enhancing consistency, so you can focus on higher-level tasks.",
    "category": "Product",
    "categories": [
      "Product"
    ],
    "date": "2024-12-30",
    "thumb": "/assets/videos/ai-voice-agents-for-debt-collection.webp",
    "youtubeId": "iWrA0IfjGDw"
  },
  {
    "slug": "fireside-chat-with-kumar-saurav-ai-voice-agents",
    "title": "Fireside chat with Kumar Saurav | AI Voice Agents",
    "description": "Watch Kumar Saurav, Co-Founder & CTO of Vodex.ai, in a fireside chat with Tap Start X as he discusses how AI Voice Agents are transforming call centers and sales processes, driving efficiency and innovation in business operations.",
    "category": "Podcasts / Interviews",
    "categories": [
      "Podcasts / Interviews"
    ],
    "date": "2024-12-30",
    "thumb": "/assets/videos/fireside-chat-with-kumar-saurav-ai-voice-agents.webp",
    "youtubeId": "5KOmrdI6Qjo"
  },
  {
    "slug": "building-the-future-of-ai-virtual-agents",
    "title": "Building the Future of AI Virtual Agents",
    "description": "Makers Bar Interview with Kumar Saurav, Co-Founder & CTO at Vodex.ai",
    "category": "Podcasts / Interviews",
    "categories": [
      "Podcasts / Interviews",
      "Overview"
    ],
    "date": "2024-12-30",
    "thumb": "/assets/videos/building-the-future-of-ai-virtual-agents.webp",
    "youtubeId": "gM7ZWrdbNNo"
  },
  {
    "slug": "scale-your-outbound-sales-motion-with-ai-voice-agents",
    "title": "Scale Your Outbound Sales Motion with AI Voice Agents",
    "description": "CEO & Co-founder, Anshul shares his fascinating journey from being an engineer in India to founding Vodex AI, a company specializing in Gen AI technology for phone call automation.",
    "category": "Podcasts / Interviews",
    "categories": [
      "Podcasts / Interviews"
    ],
    "date": "2024-12-21",
    "thumb": "/assets/videos/scale-your-outbound-sales-motion-with-ai-voice-agents.webp",
    "youtubeId": "QcX1Fi6JJOw"
  },
  {
    "slug": "ai-agent-better-than-belfort-and-cardone",
    "title": "AI Agent - Better Than Belfort and Cardone?",
    "description": "Picture this: all calls automatically identified as warm, cold, or hot based on interest level. For highly engaged leads, we can transfer them directly to your closer in real-time.",
    "category": "Overview",
    "categories": [
      "Overview"
    ],
    "date": "2024-12-20",
    "thumb": "/assets/videos/ai-agent-better-than-belfort-and-cardone.webp",
    "youtubeId": "eyt7EGvmChs"
  },
  {
    "slug": "payment-reminders-with-ai-voice-agents",
    "title": "Payment Reminders with AI Voice Agents | Live Demo",
    "description": "Designed for enterprises, this scalable solution automates outreach, ensures timely follow-ups, and improves efficiency in debt recovery processes. Watch our live demo to discover how AI is driving smarter, faster, and more effective debt collection strategies.",
    "category": "Product",
    "categories": [
      "Overview",
      "Product"
    ],
    "date": "2024-12-20",
    "thumb": "/assets/videos/payment-reminders-with-ai-voice-agents.webp",
    "youtubeId": "9-TqBwWPlMM"
  }
];

export function getFeaturedVideo(): Video {
  return VIDEOS.find((video) => video.featured) ?? VIDEOS[0];
}

export function getGridVideos(): Video[] {
  const featured = getFeaturedVideo();
  // Compares by slug, not object identity — a generated array from a JSON
  // round-trip (or any future data source) makes `v !== featured` an easy,
  // easy-to-reintroduce bug: it silently duplicates the featured video into
  // the grid the moment VIDEOS is produced by anything other than a literal
  // array where getFeaturedVideo() returns the exact same reference.
  return VIDEOS.filter((video) => video.slug !== featured.slug);
}
