// Precomputes the waveform bars + duration for each call sample, so the page
// never has to download and decode the MP3s just to draw them. Re-run after
// replacing any public/assets/call-sample-*.mp3:
//
//   node scripts/waveform-peaks.mjs
//
// Needs `ffmpeg` on PATH (decodes channel 0 to raw 32-bit float PCM). Writes
// lib/call-sample-waveforms.ts.

import { execFileSync } from "node:child_process";
import { readdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const BAR_COUNT = 30;
const MIN_PX = 6;
const MAX_PX = 30;
const SAMPLE_RATE = 48000;

const root = path.resolve(import.meta.dirname, "..");
const assetsDir = path.join(root, "public", "assets");
const files = readdirSync(assetsDir)
  .filter((f) => /^call-sample-\d+\.mp3$/.test(f))
  .sort();

const entries = files.map((file) => {
  const pcm = execFileSync(
    "ffmpeg",
    ["-v", "error", "-i", path.join(assetsDir, file), "-af", "pan=mono|c0=c0",
      "-ar", String(SAMPLE_RATE), "-f", "f32le", "-"],
    { maxBuffer: 1024 * 1024 * 1024 },
  );
  const raw = new Float32Array(pcm.buffer, pcm.byteOffset, Math.floor(pcm.length / 4));

  // Same peak-per-bucket algorithm the client-side decoder used to run.
  const samplesPerBar = Math.floor(raw.length / BAR_COUNT);
  const peaks = [];
  for (let i = 0; i < BAR_COUNT; i++) {
    let peak = 0;
    for (let j = i * samplesPerBar; j < (i + 1) * samplesPerBar; j++) {
      const abs = Math.abs(raw[j]);
      if (abs > peak) peak = abs;
    }
    peaks.push(peak);
  }
  const max = Math.max(...peaks) || 1;
  const heights = peaks.map((p) => Math.round((MIN_PX + (p / max) * (MAX_PX - MIN_PX)) * 10) / 10);
  const duration = Math.round((raw.length / SAMPLE_RATE) * 100) / 100;
  return { src: `/assets/${file}`, heights, duration };
});

const body = entries
  .map(
    (e) =>
      `  "${e.src}": {\n    duration: ${e.duration},\n    heights: [${e.heights.join(", ")}],\n  },`,
  )
  .join("\n");

writeFileSync(
  path.join(root, "lib", "call-sample-waveforms.ts"),
  `// Generated by scripts/waveform-peaks.mjs — do not edit by hand.
// Per-file waveform bar heights (px) and duration (s) for the call samples,
// precomputed so the page never downloads the MP3s until Play is pressed.

export type CallSampleWaveform = { duration: number; heights: number[] };

export const CALL_SAMPLE_WAVEFORMS: Record<string, CallSampleWaveform> = {
${body}
};
`,
);

console.log(`Wrote ${entries.length} waveform(s) to lib/call-sample-waveforms.ts`);
